#!/bin/tcsh
# testcfg <cfg filename>

eval `scramv1 runtime -csh`

echo " "
echo "Removing old $1.py"
/bin/rm $1.py

echo " "
echo "Creating new $1.py:"
cat  >  $1.py<<EOF
#!/usr/bin/env python
cfgFile="$1"
from FWCore.ParameterSet.Config import include
process = include(cfgFile)
EOF

echo " "
cat $1.py

echo " "
echo "Running python $1.py ... be patient!"
              python $1.py

echo " "
echo "Running cmsRun $1.py ... be patient!"
              cmsRun $1.py

echo " "
echo "Finished!"
